var works = [{"key":"1","name":"animalShelter","img":"https://i.ibb.co/Lhw1mLn/animal-Shelter.png"},
{"key":"2","name":"babySit","img":"https://i.ibb.co/Z1JfwKz/babySit.png"},
{"key":"3","name":"birdHouse","img":"https://i.ibb.co/3znVSTc/bird-House.png"},
{"key":"4","name":"childSupport","img":"https://i.ibb.co/m0fj0Zr/child-Support.png"},
{"key":"5","name":"cleanWater","img":"https://i.ibb.co/8NWVrRd/clean-Water.png"},
{"key":"6","name":"clearnPark","img":"https://i.ibb.co/KV3rqmx/clearn-Park.png"},
{"key":"7","name":"clothSwap","img":"https://i.ibb.co/2Zt1Mdx/cloth-Swap.png"},
{"key":"8","name":"driveSafety","img":"https://i.ibb.co/XpZ00Vm/drive-Safety.png"},
{"key":"9","name":"extraVolunteer","img":"https://i.ibb.co/BBVQ27p/extra-Volunteer.png"},
{"key":"10","name":"foodCharity","img":"https://i.ibb.co/nswN0cv/food-Charity.png"},
{"key":"11","name":"goodEducation","img":"https://i.ibb.co/pRMWjTy/good-Education.png"},
{"key":"12","name":"libraryBooks","img":"https://i.ibb.co/gz7VGBq/library-Books.png"},
{"key":"13","name":"musicLessons","img":"https://i.ibb.co/9hqR7vc/music-Lessons.png"},
{"key":"14","name":"newBooks","img":"https://i.ibb.co/rtnKThb/newBooks.png"},
{"key":"15","name":"refuseShelter","img":"https://i.ibb.co/R02RbZ9/refuse-Shelter.png"},
{"key":"16","name":"riverClean","img":"https://i.ibb.co/bRSHk1R/river-Clean.png"},
{"key":"17","name":"schoolSuffiles","img":"https://i.ibb.co/pQMhs5P/school-Suffiles.png"},
{"key":"18","name":"studyGroup","img":"https://i.ibb.co/tLs3rdc/study-Group.png"},
{"key":"19","name":"stuffedAnimals","img":"https://i.ibb.co/1JxBbk2/stuffed-Animals.png"},
{"key":"20","name":"voteRegister","img":"https://i.ibb.co/Q6fd5dc/vote-Register.png"}];

export default works;